* Problem 1
** dzielimy 1-4 | 5-8 (wszystkich jest 12)
*** optimum
**** 3 zważenia wystarczą
**** 2 to za mało - adversary argument

* Problem 2
** Part I
   box #1 - 2 Black & 8 Red
   box #2 - 5 Black & 5 Red
*** A.
    If we picked a red ball, what prob is it was from box #1?
    *p(BoxOne|RedBall) = ?*

    p(RedBall) = 1/2 * 8/10 + 1/2 * 5/10 = 8/20 + 5/20 = 13/20
    p(BoxOne) = 1/2
    p(RedBall|BoxOne) = 8/10 = 4/5

    p(BoxOne|RedBall) = (4/5 * 1/2) / 13/20
    = 4/10 * 20/13 = 2/5 * 20/13 = 40/5*13 = 8/13
** Part II
*** A.
    *p(RealCarrier|Positive) = ?*

    p(RealCarrier) = 1/1_000_000
    p(Positive) = 10_000_098/1_000_000_000
    p(Positive|RealCarrier) = 99/100

    |          | Carrier | Clean       |               |
    | Positive |      99 | 9_999_999   | 10_000_098    |
    | Negative |       1 | 989_999_901 | 989_999_902   |
    |          |     100 | 999_999_900 | 1_000_000_000 |

    p(RealCarrier|Positive) =
        p(Positive|RealCarrier) * p(RealCarrier) / p(Positive)
    # TODO tysiac a nie sto
    p(RealCarrier|Positive) =
        99/100 * 1/1_000_000 / 10_000_098*1_000_000_000

* Problem 5
  Prawdopodobieństwo ciągłe -> P(a < X <= b) = całka od a do b z f(x)
  f(x) = prob. density function

  Cumulative Distribution Function
  P(X <= x)
  całka od minus nieskończoności do x z PDT

** rozwiązanie
   P(x) = 1 jeśli x w [0; 1], 0 otherwise
   (bo integral na calosci to 1 i to jedyne miejsca gdzie wykres != 0)
   CDF (<0) = 0 -> nie ma takich punktów
   CDF ([0; 1) aka x) = x, bo to uniform distribution
   CDF([1; +inf)) = 1, bo już dalej nie rośnie

   X and Y have the same P and CDF.
   M = mniejsza sposrod X i Y
   CDF(m) = P(M <=m) = 1 - P(M > m)
   m to mniejsza z nich więc:
   = 1 - P(X > m, Y > m)
   = 1 - P(X>m) * P(Y>m)  // algebraiczne wlasciwosci
   = 1 - [1 - P(X <= m)] * [1 - P(Y <= m)]  // odwrocenie
   = 1 - [1 - CDFx(m)] * [1 - CDFy(m)]  // definicja CDF wyzej
   = 1 - [1-m] * [1-m]  // takie wartości przyjmuje CDF
   = 1 - (1 -2m + m^2)
   = 2m - m^2

   Czyli CDFmin(m) = 2m - m^2
   Mamy CDF, ale do Expected Value potrzebujemy f(m), Prob. Density Func.
   Wiemy, że CDF to całka między -inf a m...
   ... ale tutaj również 0 a m!
   PODSTAWOWE TWIERDZENIE RACHUNKU CAŁKOWEGO mówi, że skoro zaczynają się obie od 0 (całka i f(x)),
   to ten CDF od 0 do m po wyprowadzeniu pochodnej da f(m):
   (2m - m^2)' = (2 - 2m)

   CZYLI:
   f(m) = 2 - 2m  // to Prob. Density Function

   Szukamy expected value M, czyli r(m) = m  // zeby ladnie wstawic do wzoru
   E[M] = calka miedzy 0 a 1 z m * f(m) = m * (2-2m) = (2m - 2m^2)
   F(m) = m^2 - 2/3*m^3
   F(1) - F(0) = 1 - 2/3 = 1/3

   WYNIK = 1/3
