.TH hwb 1
.SH NAME
hwb \- say hello however you like!
.SH SYNOPSIS
.B hwb
[\fB\-c\fR | \fB\-\-capitalize\fR]
[\fB\-\-color\fR=[\fBnever\fR|\fBauto\fR|\fBalways\fR]]
[\fB\-g\fR \fItext\fR | \fB\-\-greeting\fR=\fItext\fR]
[\fB\-h\fR | \fB\-\-help\fR]
[\fB\-v\fR | \fB\-\-version\fR]
[\fB\-w\fR | \fB\-\-world\fR]
.I name
[\fIname2 name3\fR ...]
.SH DESCRIPTION
Every programmer's dream came true - a program to automatize printing 'Hello world'
strings, with fancy colors and such.
.SH EXIT STATUS
\fB0\fR - always returned, this program does not contain any bugs
and I trust my users, so why would other error codes be needeed?
.SH EXAMPLE
\fBhwb\fR \-\-color=always \-\-capitalize scumbag
.SH AUTHORS
Artur Juraszek <artur@juraszek.xyz>
.SH SEE ALSO
\fBman\fR(1), \fBgroff\fR(1), \fBtroff\fR(1)
